#!/usr/bin/env node
// Builds the slim Hakkadict lookup index consumed by the content-script
// selection-popup feature. Reads the pinned HakkaDictMoeDataMirror submodule,
// strips heavy fields, generates normalized lookup keys for every entry, and
// writes src/data/dict-index.json + dict-version.json. Treated as a build
// artifact (gitignored), regenerated by `npm run build` via `prebuild`.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  normalizeLookup,
  normalizeFolded,
} from "../src/shared/normalize.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const mirrorRoot = resolve(root, "lib/HakkaDictMoeDataMirror");
const mirrorManifestPath = resolve(mirrorRoot, "public/manifest.json");
const outDir = resolve(root, "src/data");
const outIndex = resolve(outDir, "dict-index.json");
const outVersion = resolve(outDir, "dict-version.json");

if (!existsSync(mirrorManifestPath)) {
  console.error(
    `[build-index] missing ${mirrorManifestPath}\n` +
      `Run: git submodule update --init --recursive`,
  );
  process.exit(1);
}

const mirrorManifest = JSON.parse(readFileSync(mirrorManifestPath, "utf8"));
const version = mirrorManifest.latest_version;
const dataPath = resolve(mirrorRoot, mirrorManifest.files.json);
if (!existsSync(dataPath)) {
  console.error(`[build-index] missing data file ${dataPath}`);
  process.exit(1);
}

console.log(`[build-index] reading ${dataPath}`);
const raw = JSON.parse(readFileSync(dataPath, "utf8"));

// Trim whitespace; convert ideographic-space sentinel (　) and other
// whitespace-only strings to "".
function clean(v) {
  if (typeof v !== "string") return "";
  const t = v.trim();
  if (!t) return "";
  // Upstream uses U+3000 IDEOGRAPHIC SPACE as a null-sentinel in some cells.
  if (/^[\s 　]+$/.test(t)) return "";
  return t;
}

const DIALECT_MAP = {
  "四縣腔": "siyen",
  "南四縣腔": "namSiyen",
};

const entries = [];
const keys = Object.create(null);
const keysFolded = Object.create(null);

function pushKey(map, key, idx) {
  if (!key) return;
  let arr = map[key];
  if (!arr) {
    arr = [];
    map[key] = arr;
  }
  if (arr[arr.length - 1] !== idx) arr.push(idx);
}

for (const row of raw) {
  const dialect = DIALECT_MAP[row.Dialect];
  if (!dialect) {
    console.error(
      `[build-index] unexpected Dialect "${row.Dialect}" at 序號 ${row["序號"]}`,
    );
    process.exit(1);
  }
  const entry = {
    dialect,
    seq: row["序號"],
    term: clean(row["詞目"]),
    reading: clean(row["音讀"]),
    readingSymbol: clean(row["音讀（符號）"]),
    pfs: clean(row["PFS"]),
    pfsInput: clean(row["PFS輸入式"]),
    gloss: clean(row["釋義"]),
    example: clean(row["例句"]),
  };
  const idx = entries.length;
  entries.push(entry);

  for (const field of [
    entry.term,
    entry.reading,
    entry.readingSymbol,
    entry.pfs,
    entry.pfsInput,
  ]) {
    if (!field) continue;
    pushKey(keys, normalizeLookup(field), idx);
    pushKey(keysFolded, normalizeFolded(field), idx);
  }
}

const index = { version, entries, keys, keysFolded };

mkdirSync(outDir, { recursive: true });
writeFileSync(outIndex, JSON.stringify(index));
writeFileSync(
  outVersion,
  JSON.stringify({ version, builtAt: new Date().toISOString() }, null, 2),
);

const rawSize = (JSON.stringify(index).length / 1024 / 1024).toFixed(2);
console.log(
  `[build-index] wrote ${entries.length} entries, ${Object.keys(keys).length} precise keys, ${Object.keys(keysFolded).length} folded keys (${rawSize} MB)`,
);
console.log(`[build-index]   → ${outIndex}`);
console.log(`[build-index]   → ${outVersion}`);
